# Generated by Django 6.0.6 on 2026-07-02 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_viewer_fields_and_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='image_url',
            field=models.URLField(blank=True, default='', max_length=1000),
        ),
    ]
