# Generated by Django 6.0.6 on 2026-07-02 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_client_otp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClientOTP',
        ),
    ]
